model_type: vit_t
output_csv: results/eval.csv
viz_dir: results/visuals
weights:
  - name: run1
    path: logs/best_student.pth
  - name: run2
    path: logs/best_student.pth
datasets:
  - name: val
    image_dir: dataset-1/val/image
    mask_dir: dataset-1/val/mask
